### ISSUE TITLE
PROPOSAL - Move document widths to design tokens

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1010]
This could be a `vf-document-widths` or `vf-page-grid` or such.

The use case is two-fold:

1. Moving some of the document widths to design tokens would save a lot of repetition (you can find 288px, and 76.5 em many times in the code; see screenshot)
2. It would also allow for more flexibility for non-core-EMBL projects to have a different width

![image](https://user-images.githubusercontent.com/928100/87240200-adf49280-c417-11ea-944b-2f25ff8f793e.png)

Also possible inclusions for the tokens is `vf-sass-config/variables/vf-global-custom-properties.scss` 

```css
// Native CSS properties, currently limited to document spacing.
:root {
  --page-grid-gap: 16px;
  --embl-grid-module--prime: 200px;
  --embl-grid-spacing-normaliser: 6px;
  @media (min-width: 1200px) {
    --page-grid-gap: 30px;
  }
}
```

And i think these might not be used anywhere `vf-sass-config/variables/vf-global-variables.scss`:

```css
// grid variables
$global-grid-column-gap: 1em !default;
$global-page-max-width: 76.5em !default;
```

**Comment by khawkins98** [comment]
This was done some time ago:

```yaml
props:
  - name: vf-layout--comfortable
    value: 81.25em
    type: number

  - name: vf-layout--cozy
    value: 75em
    type: number

  - name: vf-layout--compact
    value: 62.5em
    type: number
```

https://github.com/visual-framework/vf-core/blob/develop/components/vf-design-tokens/src/variables/vf-layout.yml
