### ISSUE TITLE
Component: vf-summary--news block

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1036]
The [vf-summary--news-has-image](https://visual-framework.github.io/vf-core/components/detail/vf-summary--news-has-image.html) is inline, but it's shown through component-hackary as a block in many places. 

![image](https://user-images.githubusercontent.com/928100/89271760-74413100-d63d-11ea-94e5-e9cb6153046c.png)

This is the code that seems required to do it

```css
  .summary-inline .vf-summary {
    grid-template-columns: none;
  }

  .summary-inline .vf-summary > .vf-summary__date {
    grid-row: 7;
  }

  .summary-inline .vf-summary > .vf-summary__image {
    max-width: 100%;
    margin-bottom: 16px;
  }

  @media (max-width: 600px) {
    .summary-inline .vf-summary {
      grid-row-gap: 0;
    }
  }
```

Aside: the [--has-image](https://visual-framework.github.io/vf-core/components/detail/vf-summary--news-has-image.html) demo image isn't showing. We could use the [image proxy](https://acxngcvroo.cloudimg.io/v7/https://www.embl.org/news/wp-content/uploads/2020/07/organ_formation_embryo-Hartmann-wordpress.jpg?w=300&h=200) to simplify things.

@sturobson seems like one for you, assigning.
