### ISSUE TITLE
Bug: EMBL Grid gap missing

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1211]
After the latest embl-grid update (#1206) the grid gap seems missing:

![image](https://user-images.githubusercontent.com/928100/97886644-21a10f00-1d29-11eb-8fde-f00555ea18f3.png)

The grid gap doesn't seem to be compiling:

```css
@media (min-width: 75em) {
  :root {
    --page-grid-gap: map-get($vf-spacing-map, vf-spacing--800);
  }
}
```

I think `components/vf-sass-config/variables/vf-global-custom-properties.scss`

```css
    --page-grid-gap: map-get($vf-spacing-map, vf-spacing--800);
```

should be
```css
    --page-grid-gap: #{map-get($vf-spacing-map, vf-spacing--800)};
```

(Note this version is not yet visible on https://visual-framework.github.io/vf-core/components/embl-grid/ as we haven't yet tagged a release)
