### ISSUE TITLE
Images are always left aligned

### ISSUE THREAD

**Issue by prakashebi** [visual-framework/vf-core#1583]
Images are aligned left even if we set it to align center in WordPress.

VF applies **margin:0** to figure elements which overrides margins set by WordPress editor.

**VF margins to figure**

```
.vf-content figure:not([class*=vf-]) {
    margin: 0;
}
```

**WordPress margins to figure**

```
.wp-block-image .aligncenter {
    margin-left: auto;
    margin-right: auto;
}
```

**It will helpful if the alignment can be set by the editor as per their content requirements.**

Screenshot also attached.

![Screenshot 2021-06-11 at 14 58 15](https://user-images.githubusercontent.com/45974822/121664920-9e694800-cac5-11eb-9302-d0819cebcd1e.png)

**Comment by khawkins98** [comment]
Background: The reasoning at play here is that the post is wrapped in a `.vf-content` class, so the VF is attempting to apply what it thinks are reasonable defaults.

I don't the default, in this case, is very good. 

[Looking to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure), I think we can improve on `.vf-content figure` 

Something like:

```css
.vf-content figure:not([class*="vf-"]) {
    display: flex;
    flex-flow: column;
    padding: 5px;
    margin: auto;
    width: min-content;
}

.vf-content figure:not([class*="vf-"]) img:not([class*="vf-"]) {
    height: auto;
    width: max-content;
}
```

Actions:

- [ ] Trial on vf-content
- [ ] Pass for testing on WP
- [ ] Do we somehow exclude impages wrapped in `.wp-block-image`?
