### ISSUE TITLE
An edit link under the EBI footer

### ISSUE THREAD

**Issue by prakashebi** [visual-framework/vf-core#1628]
On pulling the EBI header and footer, an edit link is visible underneath. I think that's coming from the WordPress content body etc. but we don't need that in rendered component.

Example page https://dev.trainingcontent.embl.org/cancer-genomics-2021

![Screenshot 2021-07-14 at 17 08 49](https://user-images.githubusercontent.com/45974822/125616395-232aacc4-a11b-4053-b0d3-3ddee254e937.png)
![Screenshot 2021-07-14 at 17 09 32](https://user-images.githubusercontent.com/45974822/125616424-9c190cc0-21ea-414d-a848-590ef5ad0d46.png)

**Comment by khawkins98** [comment]
This is part of the contentHub editor tooling, it normally would not be shown (unless activated):

```css
.embl-conditional-edit {
    display: none;
}
```

However the page has some local CSS that is overriding this:

```css
.vf-link {
    display: flex;
    align-items: center;
    &: hover svg { fill: #4a8bff; };
}
```

The above CSS seems quite broad to apply to every vf-link on the page, perhaps you can narrow the scope? Or is it even needed?
