### ISSUE TITLE
Chore: add a `nowrap` utility class

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#531]
There are always cases where text shouldn't be split; perhaps we do it like:

```css
.vf-u-text--nowrap {
    white-space: nowrap;
}
```
