### ISSUE TITLE
VF Search inline is a little ___- out of line

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#575]
https://visual-framework.github.io/vf-core/components/detail/vf-search--inline.html looks like:

![image](https://user-images.githubusercontent.com/928100/65601431-5c6f3a00-dfa2-11e9-92c5-a92edd479e0f.png)

I suspect this is as:

```css
.vf-form__input {
    position: relative;
    top: 24px;
}
```

But I'm not sure how it's intended to work, and I know there are pending fixes to vf-form. 

Maybe it's something to check in on after the vf-form refactor is done (#530)
