### ISSUE TITLE
Enhancements for vf-form

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#762]
A recent page used a `fieldset` and prompted a few things:

- support for `fieldset` (`.vf-form--fieldset`)
- support for `legend` (`.vf-form--legend`)
- positioning of the checkbox and two-line text wrap

![image](https://user-images.githubusercontent.com/928100/74422245-986e4300-4e4e-11ea-978d-fc22efc11716.png)

Code for that is at https://gitlab.ebi.ac.uk/emblorg/html-sites/embl-jobs-pages/blob/master/src/components/vf-local-overrides/vf-local-overrides.scss

```css
// @todo: backport these to vf-form
// .vf-form__item is position: relative element and
// this stops the hidden input from breaking layout.
// This might also be helpful for radio buttons, but not tested.
.vf-form__checkbox + .vf-form__label {
  left: 0;
}

// handle two line labels
.vf-form__label {
  display: grid;
  grid-template-columns: minmax(10px, 30px) 1fr;
  align-items: baseline;
}

// add fieldset element styling
.vf-form--fieldset {
  border: 2px solid set-ui-color(vf-ui-color--grey);
  margin-bottom: map-get($vf-spacing-map, vf-spacing--lg);
}

// add legend element styling
.vf-form--legend {
  @include set-type(text-heading--5, $custom-margin-bottom: map-get($vf-spacing-map, vf-spacing--sm));
}

```

I figure give it a day or two to settle and if it seems to be working, make a PR that looks at it more holistically in the context of vf-core.
