### ISSUE TITLE
COMPONENT - Definition list

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#914]
Definition lists are quite useful in the right place, we should support them.

The vanilla HTML styling is rubbish:

![image](https://user-images.githubusercontent.com/928100/81375332-96401b80-9101-11ea-814d-50843379958d.png)

Here's a simple placeholder look:

![image](https://user-images.githubusercontent.com/928100/81375398-b7087100-9101-11ea-9fb8-01a2623e79c2.png)

```css
.vf-dl {
  margin-top: 0; // reset
}
.vf-dl--dt {
  @include set-type(text-body--2, $custom-margin-bottom: 12px);
  font-weight: 500;
}
.vf-dl--dd {
  @include set-type(text-body--2, $custom-margin-bottom: 24px);
}
```

Request:

- [ ] a "`vf-dl`" (`vf-definition-list`?) component
- [ ] support for `.vf-content dl`
